[package]
name = "qr2text"
version = "0.1.0"
authors = ["Ayose <ayosec@gmail.com>"]
exclude = [ "imgs/*" ]

[dependencies]
qrcode = { version = "0.4", default-features = false }

[profile.release]
panic = "abort"
lto = true
